name: Run Geocode ETL

on:
  workflow_dispatch:
    inputs:
      since:
        description: "Only process rides on/after this date (YYYY-MM-DD). Blank = all."
        required: false
        default: ""
      max_rides:
        description: "Cap number of rides to process (0 = no cap)."
        required: false
        default: "0"
      places:
        description: "Rounding places for cache key (3≈120m, 2≈1.1km)."
        required: false
        default: "3"
      provider:
        description: "Reverse geocoder: opencage | nominatim"
        required: false
        default: "opencage"
      throttle_s:
        description: "Seconds to sleep per lookup (use 1.0 for Nominatim)."
        required: false
        default: "0.25"
      checkpoint_minutes:
        description: "Optional: write results every N minutes (0 = only at end)."
        required: false
        default: "0"

permissions:
  contents: read

concurrency:
  group: geocode-etl
  cancel-in-progress: false

jobs:
  run-geocode-etl:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests gspread gspread-dataframe google-auth

      - name: Versions
        run: |
          python - <<'PY'
          import sys, pandas, numpy, requests
          print("Python:", sys.version.split()[0])
          print("pandas:", pandas.__version__)
          print("numpy:", numpy.__version__)
          print("requests:", requests.__version__)
          PY

      - name: Run Geocode ETL
        env:
          # Required
          GCP_SVC_JSON: ${{ secrets.GCP_SVC_JSON }}
          SHEET_ID:     ${{ secrets.SHEET_ID }}
          # Provider choice
          OPENCAGE_API_KEY:     ${{ secrets.OPENCAGE_API_KEY }}
          NOMINATIM_USER_AGENT: ${{ vars.NOMINATIM_USER_AGENT }}
          # Fallback coords
          SECRET_LAT:   ${{ secrets.SECRET_LAT }}
          SECRET_LON:   ${{ secrets.SECRET_LON }}
          HOME_LAT:     ${{ secrets.HOME_LAT }}
          HOME_LON:     ${{ secrets.HOME_LON }}
          # Inputs → env
          RG_SINCE:          ${{ inputs.since }}
          RG_MAX_RIDES:      ${{ inputs.max_rides }}
          RG_PLACES:         ${{ inputs.places }}
          RG_PROVIDER:       ${{ inputs.provider }}
          RG_THROTTLE_S:     ${{ inputs.throttle_s }}
          RG_CHECKPOINT_MIN: ${{ inputs.checkpoint_minutes }}
        run: |
          echo "[RG] Starting Geocode ETL…"
          python geocode_etl.py
