name: Weather smoke test

on:
  workflow_dispatch:  # run manually from the Actions tab

jobs:
  weather-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Show commit and repo root
        run: |
          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"
          git rev-parse HEAD
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Assumes weather_smoke_test.py is in the repo root.
      - name: Run weather smoke test
        run: python weather_smoke_test.py
        env:
          HOME_LAT: ${{ secrets.HOME_LAT }}   # e.g., 41.636
          HOME_LON: ${{ secrets.HOME_LON }}   # e.g., -71.176
