name: Run Weather ETL

on:
  # Manual run with optional filters
  workflow_dispatch:
    inputs:
      since:
        description: "Only process rides on/after this date (YYYY-MM-DD). Leave blank for all."
        required: false
        default: ""
      max_rides:
        description: "Cap number of rides to process (0 = no cap)."
        required: false
        default: "0"
      flush_every:
        description: "Flush partial results to Sheets every N rides."
        required: false
        default: "25"
  # Auto-run when these files change
  push:
    paths:
      - "weather_etl.py"
      - "requirements.txt"
      - ".github/workflows/run-weather-etl.yml"

permissions:
  contents: read

concurrency:
  group: weather-etl
  cancel-in-progress: false

jobs:
  run-weather-etl:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Fallback if you don't keep a requirements.txt
            pip install pandas numpy requests gspread gspread-dataframe google-auth
          fi

      - name: Show versions (debug)
        run: |
          python - <<'PY'
          import sys, pandas, numpy, requests
          print("Python:", sys.version.split()[0])
          print("pandas:", pandas.__version__)
          print("numpy:", numpy.__version__)
          print("requests:", requests.__version__)
          PY

      - name: Run Weather ETL
        env:
          # Required secrets (set these in your repo settings → Secrets and variables → Actions)
          GCP_SVC_JSON: ${{ secrets.GCP_SVC_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          # Provide both names for compatibility, care for missing long/lat
          SECRET_LAT:   ${{ secrets.SECRET_LAT }}
          SECRET_LON:   ${{ secrets.SECRET_LON }}
          HOME_LAT:     ${{ secrets.HOME_LAT }}
          HOME_LON:     ${{ secrets.HOME_LON }}
          # Optional tuning (from workflow_dispatch inputs)
          WX_SINCE: ${{ inputs.since }}
          WX_MAX_RIDES: ${{ inputs.max_rides }}
          WX_FLUSH_EVERY: ${{ inputs.flush_every }}
        run: |
          echo "[WX] Starting Weather ETL…"
          python weather_etl.py
